#include<iostream>
#include<cstdio>
using namespace std;

int main(){
  int n, m;
  int out = 0;
  cin>>n>>m;
  int a[n];
  int b[m];

  for (int i = 0; i < n; i++)
  {
    cin>>a[i];
  }
    for (int i = 0; i < m; i++)
  {
    cin>>b[i];
  }

  for (int i = 0; i < b[0] && i > a[n-1]; i++)
  {
    for (int j = 0; i < ; i++)
    {
      /* code */
    }
    
    if (i%)
    {
      /* code */
    }
    
  }
  


  
  return 0;
}